<?php
echo $this->tag->linkTo(['../login/logout','Logout','class'=>'nav-link px-3 btn']);
echo "The Date is :- ".$date."<br>";
echo "The Time is :- ".$timezone."<br>";
?>

<?php
if ($users->count() > 0) {
    ?>
   
    <a href="#" class="nav-link" id="user" ><h4>Users</h4></a>
    <div id="userdiv">
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Password</th>
            
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Users quantity: <?php echo $users->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($users as $user) { ?>
            <tr>
                <td><?php echo $user->id; ?></td>
                <td><?php echo $user->name; ?></td>
                <td><?php echo $user->email; ?></td>
                <td><?php echo $user->password ?></td>  
                
        <?php } ?>
        </tbody>
    </table>
    </div>

    <?php
}
?>
